#!/bin/sh
# 5GHz
uci set wireless.radio0.disabled='0'
uci set wireless.default_radio0.disabled='0'
uci set wireless.default_radio0.ssid='MiFi_5G'
uci set wireless.default_radio0.encryption='psk2'
uci set wireless.default_radio0.key='12345678'

# 2.4GHz
uci set wireless.radio1.disabled='0'
uci set wireless.default_radio1.disabled='0'
uci set wireless.default_radio1.ssid='MiFI'
uci set wireless.default_radio1.encryption='psk2'
uci set wireless.default_radio1.key='12345678'

uci commit wireless
